services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 8080:8080
    networks:
      - custom_network
    restart: unless-stopped
  backend:
    build:
      context: ./backend
    volumes:
      - db_volume:/var/lib/postgresql/data
    networks:
      - custom_network
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    depends_on:
      - db
  db:
    build:
      context: ./db
    volumes:
      - db_volume:/var/lib/postgresql/data
    networks:
      - custom_network
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  db_volume:

networks:
  custom_network:
